#!/bin/sh

set -e
set -x
mkdir -p config
aclocal

UNAME=`uname`
if [ "$UNAME" == "Darwin" ]; then
        glibtoolize --force --copy
else
        libtoolize --force --copy
fi

automake --foreign --add-missing --copy
autoconf
